inherit_from:
  - https://raw.githubusercontent.com/jgarber623/rubocop-configs/main/.rubocop.roda.yml

# Checks if the length of a block exceeds some maximum value.
Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

# Checks that spec file paths are consistent and well-formed.
RSpec/FilePath:
  SpecSuffixOnly: true

# Checks for nested example groups.
RSpec/NestedGroups:
  Max: 4

# Checks hash literal syntax.
Style/HashSyntax:
  EnforcedShorthandSyntax: either
