inherit_from:
  - https://jgarber623.github.io/rubocop-configs/.rubocop.yml
  - https://jgarber623.github.io/rubocop-configs/.rubocop-rspec.yml

AllCops:
  Exclude:
    - bin/bundle

# Checks if the length of a block exceeds some maximum value.
Metrics/BlockLength:
  AllowedMethods:
    - route

# Checks that spec file paths are consistent and well-formed.
RSpec/SpecFilePathFormat:
  Enabled: false

# Checks for nested example groups.
RSpec/NestedGroups:
  Max: 4
