require:
  - rubocop-performance
  - rubocop-rspec

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

RSpec/MultipleExpectations:
  Max: 2

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false
