services:
  web:
    image: indieweb-endpoints-cc-web
    build:
      context: .
      target: development
    container_name: indieweb-endpoints-cc-web
    entrypoint: tail -f /dev/null
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
        consistency: delegated
