services:
  web:
    image: jgarber623/indieweb-endpoints-cc-web
    build:
      context: .
      target: development
    container_name: indieweb-endpoints-cc-web
    init: true
    entrypoint: sleep infinity
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
        consistency: delegated
      - type: volume
        target: /usr/src/dependencies

networks:
  default:
    name: indieweb-endpoints-cc-network
