name: CI

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  audit-ruby:
    uses: "./.github/workflows/audit-ruby.yml"
  lint-css:
    uses: "./.github/workflows/lint-css.yml"
  lint-ruby:
    uses: "./.github/workflows/lint-ruby.yml"
  test-ruby:
    uses: "./.github/workflows/test-ruby.yml"
